### ISSUE TITLE
redundantSelf rule causes Xcode warning in array extension call to min() and max()

### ISSUE THREAD

**Issue by chrisoffner** [nicklockwood/SwiftFormat#1037]
```
public extension Array where Element == MyType {
    var smallestByImportantProperty: MyType? {
        self.min()
    }

    var largestByImportantProperty: MyType? {
        self.max()
    }
}
```
Using redundantSelf removes `self.` on both variables, which then triggers the Xcode warning:

> Use of 'min' treated as a reference to instance method in protocol 'Sequence'
> Use 'self.' to silence this warning `Fix`
> Use 'Swift.' to reference the global function `Fix`

Not sure if the Xcode warning is unnecessarily protective or if `self.` shouldn't be considered redundant here. 

Use of `--selfrequired smallestByImportantProperty, largestByImportantProperty` doesn't work but maybe I'm doing it wrong? Could somebody show me what the comma-delimited list of functions to be excluded would look like because no matter what I try it doesn't seem to work.

```
public extension Array where Element == MyType {
    func gimmeSmol() -> MyType? {
        self.min()
    }
}
```
with `--selfrequired gimmeSmol` in my config file also doesn't seem to work.

**Comment by nicklockwood** [comment]
@chrisoffner which version of SwiftFormat are you using?

**Comment by chrisoffner** [comment]
@nicklockwood  0.48.15

**Comment by nicklockwood** [comment]
@chrisoffner regarding your question, the correct syntax in this case would be `--selfrequired min,max`, because the name you supply is the function that should not have self removed from its subject or arguments, not the containing function.

However, min/max are already excluded by default, so it shouldn't be neccessary for you to do anything in this case.

Regarding your bug, I'm not able to reproduce the error on 0.48.15 - self is not removed when I run swiftformat on the example you provided with default settings. Maybe the bug depends on something else to trigger it?
