### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by fatso83** [nicklockwood/SwiftFormat#1067]
Hi, there are multiple non-updated docker images (https://github.com/slashmo/swiftformat-docker, https://hub.docker.com/r/paumesa/swiftformat, ...) around, but they are all out of date. Would be great if there would be an automatic build for each github release or just a simple Dockerfile even, so that everyone could build their own simply.

**Comment by nicklockwood** [comment]
@fatso83 I don't know much about Docker, but if you'd like to submit a github action to manually generate the DockerFile (similar to https://github.com/nicklockwood/SwiftFormat/actions/workflows/linux_build.yml), I'd be happy to include it with the releases moving forward.

**Comment by nicklockwood** [comment]
@fatso83 if you think it would make more sense to include it in the repo itself, I can also do that.

**Comment by muuvmuuv** [comment]
How's it going so far here? There are some already in the hub, but no longer updated, it seems.

**Comment by vox-humana** [comment]
Hi there,

About a year ago, I started building SwiftFormat Docker for my projects here https://github.com/vox-humana/docker-swiftformat. The main reason for using Docker for me is to have a faster and less expensive Linux machine in GitHub Actions or Bitbucket Pipeline setup. At this point, I didn't know whether somebody else needed it, and, as has been already mentioned in this thread, there were no up-to-date solutions.

Currently, the project contains:

1. All recent versions of SwiftFormat (since about nine months ago).
2. Multiplatform (amd64 and arm64) support. Find it very useful to play locally on Apple Silicon machine (also, arm64 seems like a future for the cloud CI as well).
3. Docker Hub and GitHub Packages registries support.

I can see other people are interested in this, and @nicklockwood is not against the idea. Therefore, I am happy to try to integrate an action in this repo. I probably will start with GitHub Packages integration, so docker containers belong to this repo.

Cheers
