### ISSUE TITLE
Disappeared from Editor Menu

### ISSUE THREAD

**Issue by trahho** [nicklockwood/SwiftFormat#1133]
I use SwiftFormat for Xcode all the time. This morning it suddenly disappeared from the menu. I have no explanation.
I reinstalled SwiftFormat as well as Xcode, it still does not show. I tried all the hints I found (incl. lsregister), nothing worked.
Xcode Version 13.2.1 (13C100)
SwiftFormat for Xcode Version 0.49.2 (1)
macOS Monterey Version 12.1 (21C52)
Does anyone have an idea?

**Comment by pawello2222** [comment]
I had the very same problem, SwiftFormat suddenly disappeared from Xcode. Updating macOS to Monterey 12.2.1 somehow solved the issue.

**Comment by pawello2222** [comment]
Unfortunately, it looks like the issue keeps coming back. Every time a new Xcode version is released, SwiftFormat disappears from the menu (even if I did not download the new Xcode version). Once I install the new Xcode, SwiftFormat automatically appears in the menu again. 

I have observed this pattern three times already and I started treating it as a notification for a new Xcode version 😉 

It looks like SwiftFormat is somehow checking if the user's Xcode version is the newest released and otherwise it removes itself from the menu.

**Comment by nicklockwood** [comment]
@pawello2222 I can assure you that this isn't anything that SwiftFormat is doing. It has no concept of which Xcode version you have installed, nor any reason to care if it's the latest version. I assuming this is caused by some kind of security feature (or possibly a bug) in Apple's app extension infrastructure.

**Comment by raxityo** [comment]
@pawello2222 have you tried [this suggestion](https://github.com/nicklockwood/SwiftFormat/issues/898#issuecomment-815602498) by @nicklockwood? 

It worked like a charm for me!

**Comment by pawello2222** [comment]
Xcode 13.4 released and SwiftFormat is not removed from Xcode 🎉 Maybe it was just a bug somewhere in the Apple ecosystem.

In any case thank you @nicklockwood and @raxityo for your help.

**Comment by trahho** [comment]
I had put it into the build process, but now I tried the extension again, and it works.
SwiftFormat is a super good tool, helps me to keep my code clean.
Thank you all for your help, and @nicklockwood thank you so much for this great tool.
