### ISSUE TITLE
Release checksum change

### ISSUE THREAD

**Issue by danyf90** [nicklockwood/SwiftFormat#1135]
Hello 👋 
Looks like the checksum of the source zip attached to the `0.48.6` release has changed recently (from `fa23ff3d459c153c5e93931333dbd48355b85942544fa95eaa9ba51213ba21eb` to `f5622ed18c5b63c09eb99421f236c256dadee1d98fbf69f937caaea964349365`) ⚠️ 

@nicklockwood Could you please clarify whether the change was intentional? 🙏 🤔

**Comment by nicklockwood** [comment]
I don't recall that change, but most likely it was because the tagged release didn't match the one in master due to a rebasing screwup. It's unlikely that there are any user-facing differences.

**Comment by danyf90** [comment]
Makes sense 👍 
We have noticed it today, has there been any recent rebase which have impacted such old releases? 🤔 

We just want to make sure it's not something similar to [last year CodeCov breach](https://about.codecov.io/security-update/) 😅

**Comment by nicklockwood** [comment]
It wouldn't have a been a recent rebase, it would have been a rebase that happened at the time of the release that meant the wrong version got tagged and I didn't notice until much later. This sometimes happens if I switch machines around the time of release and forget that I already tagged the release on the other machine, but usually I notice right away.

**Comment by siv-bsp** [comment]
Hi @nicklockwood  👋 

Sorry to jump into this conversation, I’m a colleague of @danyf90, and I would like to understand better this case. Your guess is that the hash change may be due to a rebase happened immediately after the `0.48.6` release (that means few days after the 24th of June 2021), is it right?

This sounds a bit strange to us, as we’ve noticed the change only today. While we do cache the binary in our continuous integration, our caches are refreshed once every few days. It seems unlikely that such caches would have lasted long enough for a change which happened several months ago to cause our checksum validations to fail only now.

I have a couple of questions that may help us to understand better what happened:
- Is it possible that the rebase happened when you did the last release (6 days ago) or in any case quite recently?
- Are there other things that may have triggered the change (like some automations)? We had a look to GitHub actions, but we haven’t noticed anything related to our problem.
- Finally, are you sure there were no unauthorised accesses?

As we know that bad things may happened, we usually take extra care in such situations, thank you for your help 🙏

**Comment by nicklockwood** [comment]
I just downloaded the 0.48.6 `Source code (zip)` from here https://github.com/nicklockwood/SwiftFormat/releases?page=2 and the checksum is `fa23ff3d459c153c5e93931333dbd48355b85942544fa95eaa9ba51213ba21eb`, which you said was the original value. So now I'm a bit confused.

**Comment by keith** [comment]
github had an issue which is now reverted

**Comment by siv-bsp** [comment]
Thanks 😊
