### ISSUE TITLE
Would SwiftFormat work better as a Swift Package Plugin?

### ISSUE THREAD

**Issue by matthewreimer** [nicklockwood/SwiftFormat#1198]
Would SwiftFormat work better as a Swift Package Plugin? Might one be able to read `.swiftformat` from the filesystem?

https://developer.apple.com/videos/play/wwdc2022/110359/

**Comment by vox-humana** [comment]
Right now, it is impossible to execute a plugin on a specific file, it is available only on a target. However, it should be possible to provide different arguments, including path to a config path. I played a bit with the idea after I saw this WWDC video https://github.com/vox-humana/SwiftFormatPlugin Probably, too early to tell.

**Comment by nicklockwood** [comment]
I'm certainly open to adding this as an option. I'm also not exactly clear what the capabilities/limitations of these new plugins are though.

**Comment by vox-humana** [comment]
Cool, maybe let's continue discussion here to find out what possible scenarios of integration might be. Happy to raise a PR if we find one 🙂
Currently, I see one potential blocker. Support for plugins in Swift Package Manager was added only in [Swift 5.6](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md), so it would require bumping toolchain version in [Package.swift](https://github.com/nicklockwood/SwiftFormat/blob/master/Package.swift) file. Swift 5.6 toolchain comes with Xcode 13.3, that's why it is a quite major bump, especially considering that Xcode 13.3 requires the latest macOS 12 Monterey. What do you think?

**Comment by nicklockwood** [comment]
@vox-humana I'd certainly want to find a way to continue to support earlier macOS/Xcode versions, but presumably that could be handled with tags or branches, or even by putting the plugin in a separate repo.

**Comment by ktoso** [comment]
It seems that folks over at airbnb implemented a plugin that shells out to SwiftFormat over here: https://github.com/airbnb/swift/pull/168

That could likely serve as inspiration here and have SwiftFormat offer its own provided one :-)
Hope this helps!

**Comment by MarcoEidinger** [comment]
I maintain a Swift Package (Command) Plugin to format source code with SwiftFormat in a separate repository: https://github.com/MarcoEidinger/SwiftFormatPlugin

![Demo in Xcode](https://user-images.githubusercontent.com/4176826/179352584-db7f7f42-452c-4a42-a329-01b115a237a7.gif)

I decided that the plugin shall be triggered by the user (= command plugin). But there is also an option to create a plugin that gets executed automatically during the build (= build tool plugin). SwiftLint recently added a build tool plugin.

@nicklockwood it should be possible to add a plugin to your repo without changing/increasing swift-tools-version by using `#if swift(>=5.6)` appropriately.
