### ISSUE TITLE
Confusing how to enable/disable certain rules

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#122]
I'm reading through the documentation and trying to figure out how to make certain rules activate, and the interface is not always explicit, nor matching my expectations.

Right now I'm trying to enable a whole bunch of rules, and having trouble with them.
I'm not sure whether the parameter format should be `--enable redundantGet`, `--redundantGet`, or if `redundantGet` is enabled by default (though I don't think so since it's not formatting it properly in my project. There are also one-off rules such as `--header strip` I believe, which have a different format, but I can understand the different needs. 

One suggestion would be to update the documentation, both to show how to enable/disable each rule. More practically, it might make sense to make `swiftformat --rules` output relevant information, whether the rule is enabled or disabled by default, how to invoke it, and potentially if a config option ever becomes possible, whether it's enabled/disabled in your project specifically.

While I'm here, these are the rules I want to enable, and it would be great to figure out how to format it, relative to my current build script, since it doesn't seem to be having an effect.
```
self insert, patternlet, redundantReturn, redundantRawValues, redundantPattern, hoistPatternLet
```

```
"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" --header strip --disable unusedArguments
```

Thank you very much, hope it's not too much of a bother!

**Comment by nicklockwood** [comment]
@mergesort thanks for the feedback - I can see there's a lot of room for improvement in the documentation!

> trying to figure out how to make certain rules activate, and the interface is not always explicit, nor matching my expectations.

The source of the confusion is probably that SwiftFormat has both *rules* and *options*, which are separate concepts. The rules map to the actual functions that do the formatting. The options are configuration that is used by those rules. Rules can only be enabled or disabled. Options can accept arbitrary parameters, and a given option might affect multiple rules.

Options are set using `--optionname value`. The options are all documented in the command-line help, but not in the README.

Rules are enabled/disabled using `--enable/disable ruleName` and are all documented in the README, but not in the help.

Historically you could only configure the rules via options - the ability to enable/disable rules was added later, hence the slightly confusing API and documentation discrepancies.

> I'm not sure whether the parameter format should be --enable redundantGet, --redundantGet, or if redundantGet is enabled by default (though I don't think so since it's not formatting it properly in my project.

Almost all rules, including `redundantGet` are enabled by default, and the `redundantGet` rule has no related options - it can only be either enabled or disabled. If it's not doing what you expect, that may be a bug. Please file that as a separate issue and I'll investigate.

>One suggestion would be to update the documentation, both to show how to enable/disable each rule. 

They all follow the same pattern, but the pattern is clearly non-obvious. I'll update the docs to make it clearer.

>More practically, it might make sense to make swiftformat --rules output relevant information, whether the rule is enabled or disabled by default

It does, in fact already do this. Disabled rules have `(disabled)` next to them, but since only the `trailingClosures` rule is disabled by default you probably missed it :-)

>While I'm here, these are the rules I want to enable, and it would be great to figure out how to format it, relative to my current build script, since it doesn't seem to be having an effect.

All the rules you've listed (`redundantReturn`, `redundantRawValues`, `redundantPattern`, `hoistPatternLet`) are enabled by default, so if they don't appear to be working, please file bugs for any code that isn't being formatted correctly.

`self insert` is an option, so you need to add it to your arguments as `--self insert`, i.e.

    "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" --header strip --disable unusedArguments --self insert

`patternlet` is the configuration option for the `hoistPatternLet` rule. It accepts either a `hoist` argument (the default) or `inline`. If you want the hoist behavior, you don't need to do anything. If you want the inline behavior, add `--patternlet inline` to your arguments.

Hope that clears things up a bit!

**Comment by nicklockwood** [comment]
@mergesort I've improved the documentation in the README. Can you let me know if you think it's clear enough now, or still needs further clarification?

**Comment by mergesort** [comment]
Thank you for taking care of this, the difference through your explanation above, and the README is significantly clearer and easier to parse. 🙂
