### ISSUE TITLE
Xcode 14 Beta 4 fails to build with swiftformat script

### ISSUE THREAD

**Issue by brzzdev** [nicklockwood/SwiftFormat#1235]
Haven't changed anything except for updating Xcode, and now I get 
`error build: Command PhaseScriptExecution failed with a nonzero exit code`.

Removing the swiftformat script fixes it. Adding it back consistently errors out.

Might be the fault of Xcode, obviously I know it's a beta, so bugs are to be expected.
I see a "Run Build Tool Plug-ins" phase that I don't remember being there before. Unmoveable and unremovable. Maybe that's related?

**Comment by nicklockwood** [comment]
I'm not sure I understand what you mean by "swiftformat script"? Are you talking about a build-phase script that runs the swiftformat command-line tool?

If it's failing, it may be because swiftformat is returning an error - can you check the console logs, or try running swiftformat manually and seeing what it prints in the terminal?

**Comment by PaulDoesDev** [comment]
Yeah, it's the build-phase script. Apologies if that wasn't clear.

I get `.../DerivedData/AppName-fmlstsgjmrcrlxbexudzyairwwww/Build/Intermediates.noindex/AppName.build/Debug-iphoneos/AppName.build/Script-DA1996E0284ADBCC00469280.sh: line 5: 33369 Segmentation fault: 11  swift run -c release swiftformat "$SRCROOT"` in the build logs.

Swift format run manually from terminal still works perfectly, which is why I'm assuming it's a Xcode beta 4 issue.

**Comment by nicklockwood** [comment]
It seems like your script is building swiftformat from source rather than running the prebuilt binary? Probably is something to do with the swift toolchain in that cases

**Comment by PaulDoesDev** [comment]
I'm just using the standard build script with a BuildTools folder from the readme. Is it an issue on my end? Have you had a chance to try it on the beta version yet? I have two different projects SwiftFormat was working in and they both won't run with that script since beta 4.

I'll just use the locally installed version of the script for now.

**Comment by squarefrog** [comment]
I used this today with beta 4. Set it up using SPM and the guide in the read me. It worked well. 

I did get the nonzero exit code message, but that was my fault as I was running it with linking enabled.
