### ISSUE TITLE
Inconsistent while formatting method with single argument.

### ISSUE THREAD

**Issue by aksswami** [nicklockwood/SwiftFormat#147]
Before swift formatter:-
`func closeButtonPressed(sender: UIButton)`

After SwiftFormatter:-
`func closeButtonPressed(sender _: UIButton)`

This causes issue with @IBAction methods and also other places. I understand that `sender` should be replaced with `_` if we are not using `sender` inside the function. But above changes the function name itself.

**Comment by nicklockwood** [comment]
@aksswami is your project Swift 2.x or 3?

For 2.x this could be a breaking change, and you should disable the rule. For Swift 3.x the two function signatures above are equivalent, and I'd be very surprised if this breaks anything in your project.

**Comment by aksswami** [comment]
My project is currently in Swift 3.x and it was migrated from swift 2.x. The problem is with @IBOutlet specific. In xml it gets linked 'closeButtonTappedWithSender', but formatter changes the signature to 'closeButtonTapped'.

And you are saying that both signatures are same, but in 
'func mapping(_ map: T)' the argument is 'map' whereas in 'func mapping(map _: T)' the label is 'map'.

**Comment by nicklockwood** [comment]
@aksswami this is very strange.

From Swift's point of view, the two signatures *are* the same, because the argument name doesn't affect the method name, only the label does, so both methods have the signature `closeButtonPressed(sender:)` when called from Swift, and that should also translate to the same selector in Objective-C: `closeButtonPressedWithSender:`

As you can see from this playground screenshot, that seems to be that case. Changing the argument name doesn't matter - only the label affects the signature.

![Uploading Screen Shot 2017-06-09 at 09.46.53.png…]()

It's possible that you've found some kind of bug either in the Swift->Obj-C converter, or possibly in Interface Builder's binding logic. I'd be really interested if you could create a minimal project that reproduces the issue - and I'm sure Apple would be interested too!

If you can provide a simple repo case then I might be able to add a fix to SwiftFormat where it skips this rule for @IBActions or something.

In the meantime, you can work around this by renaming the selector. Since you aren't using the sender argument, you could just remove it. Or if you prefer, you could rename the method to:

    func closeButtonPressed(_: UIButton)

Which retains the (unused) argument, but will make the selector binding behave consistently. Note: Both of these approaches will require rebinding the action in IB.

Alternatively, you could add this argument to the SwiftFormat command line to disable the rule:

    `--disable unusedArguments`

**Comment by aksswami** [comment]
@nicklockwood Thanks for the detailed explanation. I will try to create a sample repo, If possible.

**Comment by nicklockwood** [comment]
@aksswami any update on this? Or should I close it.

**Comment by aksswami** [comment]
@nicklockwood Closing this for now, Was not able to reproduce this.

**Comment by nicklockwood** [comment]
Thanks for following up 👍
