### ISSUE TITLE
Does not work on Xcode 15

### ISSUE THREAD

**Issue by nikitavoloboev** [nicklockwood/SwiftFormat#1473]
Followed instructions to install, then press on:

![CleanShot 2023-06-19 at 16 42 50@2x](https://github.com/nicklockwood/SwiftFormat/assets/6391776/9a9c9237-d69a-41af-8243-f596ef657e67)

And then save file and nothing happens.

**Comment by nicklockwood** [comment]
I don't think there's a specific rule that would change anything in that file.

The dot on its own line should probably have a rule, but it doesn't currently.

The string literal with extra spaces in it is not something that can be auto-fixed as it might be intentional. Everything else seems correctly formatted.

**Comment by nikitavoloboev** [comment]
Thank you.

Is it hard to modify SwiftFormat with user custom rules?

**Comment by nicklockwood** [comment]
It depends on the rule. The rules are written in Swift, so you can't add new rules without recompiling the source code. Rules operate on a flat array of tokens, so things that require type information are tricky.

A rule like "a dot should never be both followed and preceded by a linebreak" would be pretty straightforward, but it might make more sense to bundle it into an existing rule like "spaceAroundOperators" rather than create a new one.
