### ISSUE TITLE
Self option adds self to type(of:) 

### ISSUE THREAD

**Issue by andrewcl** [nicklockwood/SwiftFormat#151]
When referencing class methods I tend to write
`type(of:self).someMethod()`
instead of 
`Foo.someMethod()`
as it eliminates the need to change every `Foo` call when refactoring.

Using SwiftFormat with the `self` option set to `insert` has been modifying my 
`type(of: self)`
calls to the following
`self.type(of: self)`

Would you require any additional information to diagnose this issue? 

On a separate note, it seems the self option should include an `ignore` option to allow mixing of the `insert` and `remove` stype options to exist in the project.

**Comment by nicklockwood** [comment]
I'm assuming that you have a "type" property defined in that class?

If so, this actually won't compile in Swift 4 - you would have to write `swift.type(of: self)` instead to avoid ambiguity.

I agree it's a bug that SwiftFormat breaks your code in Swift 3 though. I'll need to add a special case for type(of:).

Ps: to ignore self instead of always inserting or removing, use `--disable redundantSelf` to disable the rule completely. This works with any rule.

**Comment by nicklockwood** [comment]
Fixed in 0.29.2
