### ISSUE TITLE
pre-commit script commits unstaged changes

### ISSUE THREAD

**Issue by timothy-volvo** [nicklockwood/SwiftFormat#155]
If a file has staged and unstaged git changes, the pre-commit sample script commits all the changes as the swiftformat is executed against the working file.

**Comment by nicklockwood** [comment]
I don't know how to solve this. I'd be happy to accept a PR if you know what needs to be done.

**Comment by Johennes** [comment]
@nicklockwood I think the actual problem is that the hook shouldn't actually change anything. Having an external tool change your code right before you commit might even be considered a security issue in some companies (not saying it is actually one for SwiftFormat of course).

I think what would be great is if SwiftFormat had something like a dry mode where it'll just print out a list of files that would have been changed but doesn't actually touch anything. Then the committer could run SwiftFormat manually after their commit was rejected, inspect the changes and re-attempt the commit afterwards.

**Comment by Johennes** [comment]
@nicklockwood Implementation-wise this might be possible to achieve by adjusting the formatter methods (e.g. `removeToken`) to not actually do anything when the "dry option" is set but instead simply to record that a change would have happened. I think that would be easier than to work it into every single rule.

WDYT?

**Comment by nicklockwood** [comment]
@timothy-volvo This should be fixed by https://github.com/nicklockwood/SwiftFormat/pull/617, feel free to reopen if not.

@Johennes --dry and --lint modes have been added since your comment.
