### ISSUE TITLE
SwiftFormat as lint-only tool

### ISSUE THREAD

**Issue by OdNairy** [nicklockwood/SwiftFormat#158]
I cannot find `lint` launch option in SwiftFormat. Is it possible to launch SwiftFormat for processing #warning's and #error's without any modifications?

**Comment by nicklockwood** [comment]
No, but this is something I want to add.

You could implement this yourself way by running with --output set to a different directory so that it doesn't overwrite the original file(s). If you run with --verbose it will tell you which rules were applied to each file, so you could pipe that to a script that then generates a lint output for any file that was modified.

**Comment by OdNairy** [comment]
Thanks for notice.
I will look how can I implement it in this repo.

**Comment by nicklockwood** [comment]
@OdNairy this feature is now available via the `—lint` option
