### ISSUE TITLE
Error with conditionalAssignment

### ISSUE THREAD

**Issue by shkhaliq** [nicklockwood/SwiftFormat#1601]
I am seeing a ton of errors with conditionalAssignment rules. This is one of them

<img width="794" alt="Screenshot 2023-12-22 at 7 44 17 PM" src="https://github.com/nicklockwood/SwiftFormat/assets/7643859/e376237e-721d-476b-85c5-f2a660a48fb4">

SwiftFormat Version: **0.52.11**
Swift version: **5.9.2**
Xcode Version: **15.1.0**

I can help provide more examples if needed

**Comment by nicklockwood** [comment]
@shkhaliq I'm having trouble reproducing this issue. When I try it with default settings the `return` keywords are removed and it compiles fine. When I try it with `redundantReturn` disabled, it leaves the code unaltered.

What settings are you using? Can you provide a standlone sample that formats incorrectly with those settings?

**Comment by calda** [comment]
@shkhaliq, what error do you get? There are some bugs in Swift 5.9 where some otherwise well-formed if/switch expressions unexpectedly fail to compile.

**Comment by shkhaliq** [comment]
Sorry this was a late night post - and yes @calda I am seeing compiler errors which has nothing to do with SwiftFormat.

I was previously seeing errors but then realized was using an outdated version of SwiftFormat

**Comment by rogerluan** [comment]
@nicklockwood any chance we can have `conditionalAssignment`'s behavior working even if `redundantSelf` is disabled? Like, [same as OP](https://github.com/nicklockwood/SwiftFormat/issues/1601#issue-2054600006), but removing those `return` statements since their presence is what causes compiler errors and they must be removed in all scenarios AFAICT. Tightly coupling 2 rules in order for 1 of them to work feels kinda hacky 😅

Thanks for your help! 🙏

**Comment by nicklockwood** [comment]
@rogerluan to be clear, you aren't seeing errors, right? It's just that `conditionalAssignment` isn't being applied to cases like the above unless `redundantReturn` is also enabled?
