### ISSUE TITLE
Improper removal of return (2)

### ISSUE THREAD

**Issue by bolshedvorsky** [nicklockwood/SwiftFormat#1751]
We've noticed a large amount of breaking changes with the `redundantReturn` introduced in 5.22.xx version of SwiftFormat. We used to have it enabled in 5.21.xx but had to disable it recently. The recent version affects 1275 files in our codebase, with 8K changes, so we can't disable it per file. It would be great to have some configuration options on this rule and disable some of the behaviours.

As an example our previous valid code:
```
    func body<T>() -> T {
        switch self {
        case .singleSelect(_, _, let body):
            return body as! T
        case .multiSelect(_, _, let body):
            return body as! T
        case .number(_, _, let body):
            return body as! T
        case .amount(_, _, let body):
            return body as! T
        }
    }
```

Is updated to invalid code with this rule:

```
    func body<T>() -> T {
        switch self {
        case .singleSelect(_, _, let body):
            body as! T
        case .multiSelect(_, _, let body):
            body as! T
        case .number(_, _, let body):
            body as! T
        case .amount(_, _, let body):
            body as! T
        }
    }
```

**Comment by nicklockwood** [comment]
What is the compiler error message for this code? It seems legitimate to me.

Perhaps the issue is that the --swiftversion for your project is set higher than the actual version you are targeting?

In any case, reducing the --swiftversion to 5.9 or lower should disable this conversion and allow you to re-enable the rule

**Comment by nicklockwood** [comment]
@bolshedvorsky any update?

**Comment by nicklockwood** [comment]
@bolshedvorsky I've updated the `redundantReturn` rule so that it won't remove conditional return statements unless the `conditionalAssignment` rule is also enabled. So hopefully by using `--disable conditionalAssignment` you should now be able to keep the `redundantReturn` enabled without seeing a huge number of changes.
