### ISSUE TITLE
Can't resolve docComments rule

### ISSUE THREAD

**Issue by NikKovIos** [nicklockwood/SwiftFormat#1800]
Steps to reproduce:

1) Create empty rule:
```
    public let testRule = FormatRule(help: "Test.") { _ in
    }
```

2) Create test:
```
func testSome() {
        let input = """
        guard let somethingTwo = test.somethingTwo else {
            return
        }
        // commentOne
        guard let somethingOne = test.somethingOne else {
            return
        }

        // commentTwo
        let something = xxx
        """

        let output = """
        guard let somethingTwo = test.somethingTwo else {
            return
        }

        // commentOne
        guard let somethingOne = test.somethingOne else {
            return
        }

        // commentTwo
        let something = xxx
        """

        testFormatting(for: input, output, rule: FormatRules.testRule)
    }
```

3) We got assert failure. docComments add third `/` to commentTwo.
```
XCTAssertEqual failed: ("[SwiftFormat.Formatter.Change(line: 10, rule: docComments, filePath: nil)]") is not equal to ("[]")
XCTAssertEqual failed: ("guard let somethingTwo = test.somethingTwo else {
    return
}

// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

/// commentTwo
let something = xxx") is not equal to ("guard let somethingTwo = test.somethingTwo else {
    return
}

// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

// commentTwo
let something = xxx")
```

4) If add to output `/// commentTwo`, than test fail with 
```
XCTAssertEqual failed: ("guard let somethingTwo = test.somethingTwo else {
    return
}
// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

// commentTwo
let something = xxx") is not equal to ("guard let somethingTwo = test.somethingTwo else {
    return
}

// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

/// commentTwo
let something = xxx")
```

P.S. orderAfter: ["docComments"] don't help

**Comment by calda** [comment]
You can probably avoid this by adding `exclude: [.docComments]` to the test case, or by updating the `input` code to have the correct `///` comment as expected by the `docComments` rule.

**Comment by NikKovIos** [comment]
I think that is not correct behaviour of the rule. Because it happen in empty test.

**Comment by calda** [comment]
`testFormatting` runs every SwiftFormat rule on the `input` code, not just the rule you specify in the method call.

**Comment by calda** [comment]
This is the same behavior Nick mentioned here: https://github.com/nicklockwood/SwiftFormat/issues/1781#issuecomment-2254099562

**Comment by NikKovIos** [comment]
Why I need to add /// in input? Look, I make an empty rule indeed to check that while testing formatter apply every rule. And it can't be right test with docs rule.

I think the doc rule works incorrect, because there are no way to conform output with input, I've mentioned in example.

Did you try my example?

**Comment by calda** [comment]
> Why I need to add /// in input?

Your test case must either satisfy the `docComments` rule, or disable the `docComments` rule with `exclude: [.docComments]`. Either is correct.

> Did you try my example?

Yes, I see your test as written fails with multiple errors. One of them is caused by the `docComments` rule.

I changed `// commentTwo` to `/// commentTwo`. Now the test case only fails with one error:

```
XCTAssertEqual failed: ("guard let somethingTwo = test.somethingTwo else {
    return
}
// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

/// commentTwo
let something = xxx") is not equal to ("guard let somethingTwo = test.somethingTwo else {
    return
}

// commentOne
guard let somethingOne = test.somethingOne else {
    return
}

/// commentTwo
let something = xxx")
```

This is the correct error. If you [diff](https://www.diffchecker.com/e7VX7PKJ/) the two texts you see that the formatted code is missing the extra blank line that you have added to the `output` text:

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/a4998d70-84de-461c-bb96-ef6fedb6b383">

This is because the implementation of `testRule` does nothing, so of course the `input` text will not be modified. If you update the rule to insert the blank line as required, the test will pass.

**Comment by calda** [comment]
If you're having trouble writing a test, it would probably be easier to share the full, real test case on a branch rather than try to debug a dummy test case like this. More than happy to help debug issues with new rules! I think this discussion is slightly confusing because the `testRule` implementation is complete empty, which is not a use case that SwiftFormat's test helpers are designed for.

**Comment by calda** [comment]
For example, I checked out your branch from #1801. I see that your new `testComments()` test case is currently failing, with a message related to the `docComments` rule.

If I update `// commentTwo` to `/// commentTwo` in both the `input` and `output`, the test case now passes:

```swift
/// This test case passes
func testComments() {
    let input = """
    guard let somethingTwo = test.somethingTwo else {
        return
    }
    // commentOne
    guard let somethingOne = test.somethingOne else {
        return
    }
    /// commentTwo
    let something = xxx
    """

    let output = """
    guard let somethingTwo = test.somethingTwo else {
        return
    }

    // commentOne
    guard let somethingOne = test.somethingOne else {
        return
    }

    /// commentTwo
    let something = xxx
    """

    testFormatting(for: input, output, rule: FormatRules.spacesWithGuard)
}
```

Alternatively, the test case would also pass if you add `exclude: ["docComments"]`:

```swift
/// This test case also passes
func testComments() {
    let input = """
    guard let somethingTwo = test.somethingTwo else {
        return
    }
    // commentOne
    guard let somethingOne = test.somethingOne else {
        return
    }
    // commentTwo
    let something = xxx
    """

    let output = """
    guard let somethingTwo = test.somethingTwo else {
        return
    }

    // commentOne
    guard let somethingOne = test.somethingOne else {
        return
    }

    // commentTwo
    let something = xxx
    """

    testFormatting(for: input, output, rule: FormatRules.spacesWithGuard, exclude: ["docComments"])
}
```

Either is fine! (I personally prefer the first approach, tweaking the `input` and `output`, since it usually results in less boileerplate per test case)
