### ISSUE TITLE
Tests failed in development

### ISSUE THREAD

**Issue by NikKovIos** [nicklockwood/SwiftFormat#1803]
410de98b2b386c83e02b3b48118eaf240c7ec09d
<img width="790" alt="image" src="https://github.com/user-attachments/assets/73057d8c-a3d1-4fa9-8687-03b0e5835fde">

**Comment by calda** [comment]
When I check out https://github.com/nicklockwood/SwiftFormat/commit/410de98b2b386c83e02b3b48118eaf240c7ec09d and run the tests, I don't see any failures. What commit are you on when you see this failure? Is it when including the changes from https://github.com/nicklockwood/SwiftFormat/pull/1804?

**Comment by calda** [comment]
I can repro this failure when I check out https://github.com/nicklockwood/SwiftFormat/pull/1804. 

This is happening because:
 1. Your new rule is now being run on all of the existing test cases
 2. The `input` and `output` code of this test case doesn't follow your rule.

e.g. the `input` code has a blank line between the two guard statements, which is not allowed by the implementation of your new rule:

```swift
guard foo else {
    return
}

guard
    let foo,
    let bar,
    lat baaz else
{
    return
}
```

An easy fix for this is to remove that blank line from the input and output. This updated test case passes on your branch:

```swift
func testPreserveBlankLineBeforeElseDoesntAffectOtherCases() {
    let input = """
    if foo {
        print("foo")
    }
    else {
        print("bar")
    }

    guard foo else {
        return
    }
    guard
        let foo,
        let bar,
        lat baaz else
    {
        return
    }
    """

    let output = """
    if foo {
        print("foo")
    } else {
        print("bar")
    }

    guard foo else {
        return
    }
    guard
        let foo,
        let bar,
        lat baaz
    else {
        return
    }
    """

    let options = FormatOptions(elseOnNextLine: false, guardElsePosition: .nextLine)
    testFormatting(for: input, output, rule: .elseOnSameLine, options: options)
}
```

Alternatively, you could add `exclude: [.spacingGuards]` to the `testFormatting` call.
