### ISSUE TITLE
{ } don't align properly with --allman when used as function arguments

### ISSUE THREAD

**Issue by wizofaus** [nicklockwood/SwiftFormat#207]
The following code:

    UIScrollView.animate(withDuration: 0.25, animations: 
       {
             doStuff()
       }, completion:
       {
            doOtherStuff()
       })

Fails to format as expected, with the { } being unaligned and weirdly placed. Nor does { get moved to the next line if originally formatted K&R style. Note this happens with just a single parameter, and even if it's anonymous.

**Comment by nicklockwood** [comment]
@wizofaus the allman formatting option isn't applied to closure braces. I agree that the indenting of the last line looks weird, but that's because it's trying to balance the closing ) with the function that called it.

It's not immediately obvious what the correct behavior should be in this situation since Allman-style indenting and inline closures don't mix very well. I'd be interested to hear your thoughts. For now though, you'll get a better result if you split the closing } and ) onto separate lines, i.e.

```swift
UIScrollView.animate(withDuration: 0.25, animations:
    {
        doStuff()
    }, completion:
    {
        doOtherStuff()
    }
)
```

**Comment by nicklockwood** [comment]
This issue seems related to https://github.com/nicklockwood/SwiftFormat/issues/187

**Comment by wizofaus** [comment]
I'd be fine if swiftformat automatically put the ) on a new line. But if --allman is on, matching { and } should always align, no matter what. Not so important that matching ( and ) align.

**Comment by nicklockwood** [comment]
@wizofaus as of 0.45.0 the code sample you gave is unchanged when using --allman indenting, so I think this is fixed? Feel free to reopen if not.
