### ISSUE TITLE
Losing file history and can't "undo" and changes

### ISSUE THREAD

**Issue by Orfeas** [nicklockwood/SwiftFormat#264]
I've noticed this issue which i'm not sure if it's known already. 

When SwiftFormat detects formatting errors in a file and updates the file, you lose the ability to "undo" any changes made previously (cmd+Z for example). From what I understand the library recreates the file, it doesn't update it so you lose the ability to backtrack your changes.

**Comment by nicklockwood** [comment]
That's correct. Unfortunately there's nothing I can do about this.

I would suggest only running the SwiftFormat command line tool when you run the unit tests, instead of on every build.

You can also use the Xcode extension for formatting code while you're working on it, which will preserve your undo history.
