### ISSUE TITLE
How to share swiftformat rules and options between collaborators on a project?

### ISSUE THREAD

**Issue by rudifa** [nicklockwood/SwiftFormat#291]
With the Editor Extension installed in Xcode, I would like to set up fixed rules and options that I could share with a partner programmer on the project, so that we could enforce and maintain consistent formatting style. 

It seems to me that we should not use `Infer Automatically from Source File` for this purpose, but rather tweak rules and options, in `SwiftFormat For Xcode app`, until we are satisfied. This way, our formatting would be consistent across the project (or several projects).

@nicklockwood from what you wrote before, it appears that there is no way to install per computer or per project `.swiftformat` file that would be accessible to the Editor Extension. Would it be possible at least to export from / import to `SwiftFormat For Xcode app`  `.swiftformat` files, to facilitate sharing of options and settings across projects and collaborators?

**Comment by nicklockwood** [comment]
@rudifa the `SwiftFormat for Xcode` app can load and save `.swiftformat` files, which are the same files used by the swiftformat command-line app. When you load a `.swiftformat` file using `SwiftFormat for Xcode` then the Xcode Extension will use the settings in that file until further notice.

You can save that `.swiftformat` file in your project, but there is no automatic sync with the Xcode Extension if the file is changed - you will have to reload the modified file using the `SwiftFormat for Xcode` app to pick up any changes.

To create that file initially, you can use:

```bash
> swiftformat —inferoptions /path/to/project —output /path/to/project/.swiftformat
```

Then you can hand-edit the file to adjust the rules to your tastes, or edit it using the GUI in `SwiftFormat for Xcode` and save over the file.

**Comment by rudifa** [comment]
Right. I should have read more carefully The Friendly Manual (README), it does say "however you can import and export different configurations using the File menu."

Perhaps you could add to the README your above remarks on loading and reloading the config file by the `SwiftFormat for Xcode` app, and the lack of automatic sync.

**Comment by nicklockwood** [comment]
@rudifa I've added some extra detail in the documentation about config file importing and sync.

**Comment by Peyo61** [comment]
I can't seem to be able to format according to my rules (Allman). I have ticked Allman in the conf, the .swiftformat file confirms that, and placed the .swiftformat file in my home directory, the project directory at 2 levels (where the project file is, and above).

No dice.

Can  you clarify where the .swiftformat file is supposed to sit ?

Many thanks,
Pierre

**Comment by nicklockwood** [comment]
@Peyo61 are you trying apply formatting using the command-line tool, or with the SwiftFormat for Xcode extension? If it's the latter, then this isn't supported. Xcode extensions don't have permission to read files outside the currently selected source file in Xcode, so you have to set all configuration through the app.

**Comment by Peyo61** [comment]
Thanks for the fast reply !

I am trying to use the Xcode menu to manually format code when it makes my eyes bleed too much.

What I did:
- ran your little app which shows all the options
- ticked Allman (no other change, except “else on new line”)
- file > Save in your app, offered to save .swiftformat which I saved in my home
- then followed the instructions on the splash screen of that app to set the system preferences properly for the extension

No success in Xcode, so then I coped the .swiftformat in “may places” near the Xcode project.

Did I miss a step ? In your reply, it’s not clear to me what “have to set all conf thru the app” means, since I believe this is the first that I did, without success (?).

Do you mean that, despite using the app, I still can only use the command line ?

I may be confused this is all new to me...

Cheers,
Pierre
_____

**Comment by nicklockwood** [comment]
@Peyo61 setting the configuration in the app as you have done should work. Exporting it as a .swiftformat file in your project is not necessary and will not work.

What happens when you run the format command - does it do nothing at all, or is it formatting the code but ignoring the options you've set?

**Comment by Peyo61** [comment]
Nothing moves, but difficult to say if it’s actually trying...

For what it’s worth, I installed the cmd-line tool with Homebrew, and if I use the --config option it works. I really prefer to get the Xcode insider tool to work if I can, but.

Pierre

**Comment by nicklockwood** [comment]
@Peyo61 hi, sorry for the delay. It looks like communication between the app and the extension is broken. I think it's some sort of signing issue. If you rebuild the extension locally from the SwiftFormat source, it should work.

To do that, open the SwiftFormat.xcodeproj switch the developer profile in the Editor Extension and SwiftFormat for Xcode targets over to your own details, then build the SwiftFormat (Editor Extension) scheme.

That should replace SwiftFormat for Xcode app inside the project with a new one built with your credentials. Check that the app is around 15MB. If it's a lot less it means it hasn't embedded the extension correctly and you should delete it and rebuild.
