### ISSUE TITLE
Add silent/quiet option for command line tool

### ISSUE THREAD

**Issue by mgrebenets** [nicklockwood/SwiftFormat#300]
Hi there

This is a feature request for adding _silent / quiet_ option to command line tool.

# Problem

SwiftFormat is not silent by default, and by "not silent" I mean it **always** prints summary output to stdout.
For example:

```
swiftformat completed. 2/3 files updated in 0.05s
```

This is usually not the problem, but becomes an issue when you want to use `swiftformat` as part of a script which formats the files and writes resulting diff into a file. Summary output of `swiftformat` gets appended to the diff and renders it unusable.

# Feature Request

While it's possible to come up with a workaround using wrapper (which we did), it would be nice to have a _silent_ option available out-of-the-box.

For example, SwiftLint has a `--quiet` option, which does just that.
Probably similar `-quiet` switch in SwiftFormat would be a good name choice.

**Comment by nicklockwood** [comment]
@mgrebenets a --quiet option has been added in version 0.35.4

**Comment by lassik** [comment]
Commenting on a closed issue but:

> SwiftFormat [...] always prints summary output to stdout.
> Summary output of swiftformat gets appended to the diff and renders it unusable.

In general whenever a Unix tool writes a data file to stdout, it should write all other messages to stderr, so that stdout can be redirected into a file or pipe without worry. If a diff or some code is written to stdout, all messages should go to stderr (including informational messages that aren't errors or warnings - success, status and summary messages and the like).

If this sounds complicated, it's a reasonable policy simply to always write all messages to stderr and never to stdout. Or to disable all non-error/warning messages if a data file is written to stdout.

A `--quiet` option may be useful for other purposes, but it's a long tradition to design command line tools such that it isn't necessary for users to worry about this.

**Comment by nicklockwood** [comment]
@lassik it is/was already the case that when writing the actual formatted file to stdout then it doesn't output info messages (it would be pretty useless otherwise), so I must admit I'm not exactly sure under what circumstances @mgrebenets was encountering this problem.

I think a --quiet option is sometimes desirable for just generally reducing noise in the terminal, but it probably wouldn't do any harm to write all meta-info to stderr as you suggest anyway.

**Comment by lassik** [comment]
You're right, swiftformat seems to be working fine, omitting the status info when writing to stdout.

Maybe they did something equivalent to this:

    { cat x.swift >x.swift.orig && swiftformat x.swift && diff x.swift.orig x.swift; } >x.diff

Indeed, supporting this kind of use case isn't swiftformat's responsibility. Though I guess the all-stderr policy does no harm either way :)

**Comment by lassik** [comment]
Oh, another digression... Traditionally Unix tools have been quiet on success unless they do something that takes a long time (in which case some print progress messages). The `-v` (verbose) flag is usually given once to force printing of status/summary/progress messages in all cases. Lots of tools recognize when `-v` is given more than once, with each additional `-v` causing more detailed messages to be output. Typically a single `-v` prints all the filenames on which the tool operates, while `-vv` prints details about what is done to each file. `-vv` or `-vvv` tends to be detailed enough to be considered debug information. But this is somewhat a matter of taste. Unix CLI newbies tend to be confused by the lack of output on success by default, but advanced users tend to grow to love it since you only see what matters in your terminal scrollback. Internally, the programs represent the verbosity setting as an integer (0=quiet, 1=normal, 2=v, 3=vv, 4=vvv, ...) instead of a boolean, and have functions like

    warn(msg)  { if (verbosity >= 1) print(msg) }
    info(msg)  { if (verbosity >= 2) print(msg) }
    debug(msg) { if (verbosity >= 3) print(msg) }
