### ISSUE TITLE
Replace double ampersand with comma 

### ISSUE THREAD

**Issue by tinder-garricnahapetian** [nicklockwood/SwiftFormat#315]
Add format rule that replaces `&&` with `,`.

Cases:

old
```
if true && true {
}
```

new
```
if true, true {
}
```

old
```
guard true && true else {
    return
}
```

new
```
guard true, true else {
    return
}
```

**Comment by nicklockwood** [comment]
@tinder-garricnahapetian this is now implemented in version 0.36.0.

**Comment by Panajev** [comment]
Sorry for the late note, but it is one thing that I find would make unbalanced if's statements, for example, when dealing with logical OR's vs logical AND's... :/.

**Comment by nicklockwood** [comment]
@Panajev I’m not sure I understand what you mean. FWIW though, the rule ignores cases like `if foo && bar || baz {}` because replacing && with , can alter the precedence.

**Comment by nicklockwood** [comment]
@Panajev ah I see. Well you can always disable the rule ¯\_(ツ)_/¯

**Comment by Panajev** [comment]
Sure, but this mean quite a lot of commits in quite a lot of modules and a main repo and then propagate to all branches... :/. Oh well, sometimes it would be nice to have some rules optional instead of enabled by default, but it is not that big of a deal fixing it either hehe :).

Thanks for the answers anyways!

**Comment by nicklockwood** [comment]
@Panajev is this because your app modules are split into multiple repos, each with it’s own .swiftformat file?

**Comment by Panajev** [comment]
Guilty as charged :), single config driven whitelabelled codebase with core libraries in their git submodules and their own formatting script calling swiftformat.

**Comment by Panajev** [comment]
Hey Nick, thanks for your answer!

I have considered that and maybe this is the time to switch (although again I plodded through and made the changes already lol). This is really the first time where I disagreed with a rule since we started using swift-formatter... well, the only other problem was when a rule was renamed a while ago. Normally, it was expected that our code would change not that we would disable the option hehe, which speaks well of the kind of choices made for it so far :).

We have few rules we disable, possibly a lot less than the ones we enable and/or configure... the only real trade-off would be to be more active reading the changes in the README.md over time... which is not bad actually ;).

Mmmh mmmh 🧐...
