### ISSUE TITLE
Feature request: Support reporter output for --lint option

### ISSUE THREAD

**Issue by mgrebenets** [nicklockwood/SwiftFormat#345]
Currently lint option output only says "would have updated /path/to/file".
To see which rule(s) would be applied, one would have to use `--verbose` option and then parse the output looking for keywords like "rules applied".

This is an example of what would be captured: ` -- rules applied: consecutiveSpaces`.

The feature request is to have a more detailed report for "lint" mode, e.g. support basic formatters, such as xcode, json, checkstyle, etc.

Xcode format, for example, includes error/warning keyword, full file path, line and column number and the message itself. Such a message, if printed to Xcode build log, will be automatically picked up by IDE.

Having detailed report will be very useful in CI setup.

**Comment by nicklockwood** [comment]
This is definitely something I plan to do. Linting is a secondary use-case for SwiftFormat, and it doesn't currently have enough information to track line numbers where changes were applied, but it should be possible in future.

**Comment by balitm** [comment]
I added some modifications to today's master which prints Xcode-compatible warning info and succeeded to use it in Xcode run phase before compilation:

<img width="2160" alt="Screen Shot 2019-06-18 at 21 31 09" src="https://user-images.githubusercontent.com/14824311/60037594-40fa4780-96b2-11e9-8221-45ccf8280e30.png">

@nicklockwood, These modifications are not ready for publishing in their current form, I think. As naming is not sophisticated in the patches and many `.map { }` usage might be unnecessary but the main idea is acceptable, I think. And still the performance/run time is ok.
I count the line numbers in Tokenizer's `parseLineBreak()` and added the current line number to each token. Column info also would be fine.

I hope developers of SwiftFormat can use the following patches:
[swiftformat.zip](https://github.com/nicklockwood/SwiftFormat/files/3321880/swiftformat.zip)

They can be applied in order to commit d2d0cf5c522418a88db723ecd72b0b1395cebf63

**Comment by nicklockwood** [comment]
@balitm this sounds amazing! Can you submit it as a PR against the develop branch? It doesn't matter if it's not ready to merge - I can iterate on it.

**Comment by nicklockwood** [comment]
@mgrebenets this was merged in version 0.43.0.
