### ISSUE TITLE
`isEmpty` rule being applied to `foo.count == 0` or `foo.count > 0` when foo is NSOrderedSet

### ISSUE THREAD

**Issue by jspargo** [nicklockwood/SwiftFormat#352]
Hi there 👋 

I've just updated to version 0.39.0 and I see the `isEmpty` rule is now enabled by default. In a project I'm working on we have a handful of `NSOrderedSet`s that we access in Swift (they're defined in older Objective-C classes):
```
# Objective-C:
- (NSOrderedSet *)foo;
```
before SwiftFormat:
```
# Swift:
let bar = foo.count > 0
```
after SwiftFormat:
```
# Swift:
let bar = foo.isEmpty
```
👆 Doesn't compile with error: `Value of type 'NSOrderedSet?' has no member 'isEmpty'`

I was looking at[ the method `isEmpty(_ formatter: Formatter)` in `Rules.swift`](https://github.com/nicklockwood/SwiftFormat/blob/master/Sources/Rules.swift#L3350) and it looks like this is just looking for the string `count` before doing additional logic on if and how this can be replaced with `isEmpty` - is it possible to check whether a variable is an Array type before performing the change?

I'll have a look around a bit more to see if there's a pattern in Rules.swift that I can follow to refine this rule - let me know what you think.

**Comment by nicklockwood** [comment]
@jspargo SwiftFormat doesn’t have access to type information, since it operates on each file individually. It could theoretically take types into account for variables defined in the current file, but that would be a lot of work and still wouldn’t solve the general case.

Your best option would be to disable the `isEmpty` rule, either globally or just for the files where you are using NSOrderedSet.

**Comment by nicklockwood** [comment]
@jspargo (another option would be to define`isEmpty` as an extension on `NSOrderedSet` In your project).

**Comment by jspargo** [comment]
Thanks for your quick response @nicklockwood - I'll give that second one a go!
