### ISSUE TITLE
Proposal: default file to current directory

### ISSUE THREAD

**Issue by fphilipe** [nicklockwood/SwiftFormat#419]
First off, thanks for SwiftFormat. I use it on my projects and it's great to reduce bike-shedding around syntax among the team members. High-five for that ✋ 

I want to propose a change in the CLI interface.

I always run SwiftFormat on the entire project:

    $ swiftformat .

@nicklockwood, could you imagine making the file argument optional and defaulting to the current working directory? Then I could simply run:

    $ swiftformat

Alternatively, maybe this could be achieved with a config.

Let me know what you think.

**Comment by nicklockwood** [comment]
@fphilipeit I see where you are coming from, and SwiftLint works the way you suggest, but its default behavior doesn't modify any files.

Because SwiftFormat destructively modifies files in the directory you run it in, I wanted to make sure that it was hard to do that by accident. That's why the default behavior is to show the help, and the formatting behavior requires an explicit argument.

Even if I agreed the behavior you suggest would be preferable, existing users now expect that running `swiftformat` will show the help, so changing that innocuous behavior to a potentially destructive action now would be a big no-no.

I could conceivably predicate the behavior on the presence of a `.swiftformat` file in the current directory. If a user invokes `swiftformat` in a folder containing a `.swiftformat` config file, it's probably reasonable to assume that they meant to format it, and I will consider that.

But I'm curious why it's a problem to have to type `swiftformat .` instead of just `swiftformat`? It's only a couple of extra characters.

**Comment by fphilipe** [comment]
> Because SwiftFormat destructively modifies files in the directory you run it in, I wanted to make sure that it was hard to do that by accident. That's why the default behavior is to show the help, and the formatting behavior requires an explicit argument.
>
> Even if I agreed the behavior you suggest would be preferable, existing users now expect that running `swiftformat` will show the help, so changing that innocuous behavior to a potentially destructive action now would be a big no-no.

Yeah, that's a very good point. I agree that this is better.

> I could conceivably predicate the behavior on the presence of a .swiftformat file in the current directory. If a user invokes swiftformat in a folder containing a .swiftformat config file, it's probably reasonable to assume that they meant to format it, and I will consider that.

That would be awesome! 😄 I think this is a sensible default. If I've set up 

> But I'm curious why it's a problem to have to type swiftformat . instead of just swiftformat? It's only a couple of extra characters.

It's obviously not a problem per se, just a small nuisance 😉 So feel free to discard this if you don't think it makes sense.
