### ISSUE TITLE
Fragment option is swallowing trailing newlines

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#43]
Given the following bit of code (note the trailing newline):

```swift
func doSomething() {
    // Hello
}

```

I would expect the output to be the same as the input here, however SwiftFormat is removing that trailing newline. If there were two trailing newlines, then yeah, I reckon trim one of them - but not a single trailing newline.

This is affecting #39, as a common use-case is to select a function in amongst other functions and format it. I started to add a workaround, but I think this is actually something worth solving in the library.

Thanks!

**Comment by nicklockwood** [comment]
Sorry for the radio silence, been a bit busy - anyway, here's the fix: https://github.com/nicklockwood/SwiftFormat/tree/trailing-linebreak-fix

(I'll probably just merge it into the same release as the xcode plugin rather than include it in a release on it's own, which is why I've not merged and tagged it yet)

**Comment by tonyarnold** [comment]
LGTM! :shipit:

**Comment by nicklockwood** [comment]
Fixed in 0.12.1
