### ISSUE TITLE
CLI: Providing only invalid files to CLI causes confusing output

### ISSUE THREAD

**Issue by bawjensen** [nicklockwood/SwiftFormat#467]
## Mixing invalid and valid files

I can't say I really have too much context on SwiftFormat so I can't give an opinion on how the output for this scenario _should_ go, however it does seem odd that if I provide one invalid file alongside some valid files it's simply output as `warning: ` however if I provide only that one invalid file it's suddenly an `error: `.

```sh
/path/to/dir: swiftformat ExistingFile.swift
Running SwiftFormat...
SwiftFormat completed in 0.13s.
1/1 files formatted.

/path/to/dir: swiftformat ExistingFile.swift MissingFile.swift
Running SwiftFormat...
warning: File not found at /path/to/dir/MissingFile.swift.
SwiftFormat completed in 0.11s.
1/1 files formatted.

/path/to/dir: swiftformat MissingFile.swift
Running SwiftFormat...
error: File not found at /path/to/dir/MissingFile.swift.
```

## Providing one vs. multiple invalid files

Another case that results in what I would consider confusing output is when you provide only invalid files, but more than one of them, e.g.:

```sh
/path/to/dir: swiftformat MissingFile1.swift
Running SwiftFormat...
error: File not found at /path/to/dir/MissingFile1.swift.

/path/to/dir: swiftformat MissingFile1.swift MissingFile2.swift
Running SwiftFormat...
error: File not found at /path/to/dir/MissingFile1.swift.

/path/to/dir: swiftformat MissingFile2.swift MissingFile1.swift
Running SwiftFormat...
error: File not found at /path/to/dir/MissingFile2.swift.
```

I would expect it to tell me that all files were invalid, not seemingly just cherry-pick the first.

For this case in my local testing I could "fix" it by removing these lines: https://github.com/nicklockwood/SwiftFormat/blob/1faf434f9cb85f0494f9a81900f4f26d9ed95fcd/Sources/CommandLine.swift#L553-L556, however I don't really have context on why they're there to start with.

**Comment by nicklockwood** [comment]
The idea behind the error vs warning distinction was that if you tell SwiftFormat to format a folder of files and one of them is invalid, it might be that you just didn't want to bother excluding it, and that's probably fine. Whereas if you specifically tell it to format a file or file(s) and one or all of them was invalid, that's clearly an error.

The fact that it only reports one error when explicitly given several erroneous files is probably not the correct behavior. It was originally due to a limitation of Swift only being able to throw a single Error from a function, but since I've since patched the code to return arrays of errors instead of throwing in a bunch of places, it might be OK to remove it.

I'll take a closer look - thanks.

**Comment by bawjensen** [comment]
Awesome, thanks for the context 🙂

On this point you describe:

> The idea behind the error vs warning distinction was that if you tell SwiftFormat to format a folder of files [...]. Whereas if you specifically tell it to format a file or file(s) [...].

How you've described it makes perfect sense. However one point I can clarify: in all my testing I was always explicitly providing file names, never folders.

Given that, my take is if I explicitly give SwiftFormat two files and one's erroneous, it should error just the same as if I gave you one file and it's erroneous. That just seems like bad input that the caller of the CLI should be made aware of so they can fix it ASAP.

**Comment by nicklockwood** [comment]
@bawjensen I believe this is now fixed. It now produces errors for all missing files, regardless of how many, or if there were also valid files found.
