### ISSUE TITLE
[Discussion] New file / type organization rules

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#683]
There are several rules related to file / type organization that I'd like to reintroduce to the [Airbnb Swift Style guide](https://github.com/airbnb/swift):
 - [Each type in a file should be preceded by MARK](https://github.com/airbnb/swift/issues/54)
 - [Use // MARK: to separate the contents of a type definition](https://github.com/airbnb/swift/issues/56)
- [Within each top-level section, place content in the following order](https://github.com/airbnb/swift/issues/60)
 - [Computed properties and properties with property observers should appear at the end of the set of declarations of the same kind ](https://github.com/airbnb/swift/issues/64)
 - [Add empty lines between property declarations of different kinds](https://github.com/airbnb/swift/issues/62)

Our policy is that we only include rules that can be formatted automatically (right now, either by SwiftFormat or SwiftLint).

Does these seem appropriate for a new SwiftFormat rule / set of rules?

 - These seem like they could be too niche / Airbnb-specific, so may not be worth supporting in SwiftFormat itself.
 - I'm not sure if SwiftFormat has good mechanisms for moving around entire blocks of code (since most of its rules work in terms of individual tokens in individual expressions).
 - If not added as a SwiftFormat rule, we could write our own file organization formatter (and use it alongside SwiftFormat).

Interested in hearing your thoughts on this!

**Comment by nicklockwood** [comment]
> Each type in a file should be preceded by MARK: - Typename

This is pretty easy to implement but is rather more specific than I usually like rules to be. I'm OK with adding it as a disabled-by-default rule, but if there's some way we can make it a bit more user-configurable (e.g. like the FileHeader rule) then that would sit better.

> Use // MARK: to separate the contents of a type definition

As above. Fairly easy to hard-code, but ideally there would be some simple configuration grammar to define these in terms of "add comment with given pattern before elements of type X" rather than hard-coding everything.

> Within each top-level section, place content in the following order

This seems like a pretty reasonable rule. Again it would ideally be possible to specify the order (similar to how the `--modifiersorder` option works), but I'm fine with a hard-coded order for the first pass.

> Add empty lines between property declarations of different kinds

I'm happy to add this. It seems like it might just be an enhancement of the existing `blankLinesBetweenScopes` rule. 

> I'm not sure if SwiftFormat has good mechanisms for moving around entire blocks of code (since most of its rules work in terms of individual tokens in individual expressions).

This isn't especially easy to do, but there is precedent for it - e.g. the `sortedImports` rule does something similar. Ideally I'd like to add higher-level functions for these kind of block-level manipulations, so perhaps this would be a good opportunity to extract and generalize some of that logic.

> If not added as a SwiftFormat rule, we could write our own file organization formatter (and use it alongside SwiftFormat)

The SwiftFormat framework was actually intended to support this kind of custom functionality. You can import it and use the Formatter class directly to parse and manipulate source code. (You could just use SwiftSyntax now instead, but since you're familiar with the SwiftFormat model you might find it easier).

I'd like to explore some kind of plugin mechanism for extending SwiftFormat without needing to modify the code, but beyond simple things like regex replace, I'm not really sure how that would work.

**Comment by calda** [comment]
Cool, thanks for your input! Great suggestions about potential customization options.
