### ISSUE TITLE
Extend trailingClosures/allman Rule for Brace Position.

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#790]
Currently, when I format with my personal config that contains `--allman true` rule, it properly moves braces for these to the `next-line`.  However, when I then run a build, which uses the team's `--allman false` rule, braces for trailing closures are not pushed back up to `same-line` as is needed to pass the linter.

![image](https://user-images.githubusercontent.com/20154521/98239297-9d849c80-1f5f-11eb-8db1-ec13b85e6d86.png)

I tested on both `0.45.6` and `0.47.2`, so I am not sure when this was introduced because I do not recall having the issue before.  Is this something we can get adjusted back?  Perhaps, similar to `--guardElse same-line` that we can add to the team config to make sure it goes back?

**Comment by nicklockwood** [comment]
I suspect what changed is that `--allman` previously wasn't applied to closure braces, and now is.

The reason I don't move the braces back to the previous line is because this could cause the line to exceed to preferred wrap width. Since I don't have a general line-unwrapping feature, it's not very easy to do this.

I'll give it some more thought - let me know if you have any suggestions.

**Comment by PompeiaPaetenari** [comment]
Is this a case where we need a secondary/tertiary pass to do "clean-up" of other rules such as handling only the whitespace rules separate of replacement and movement of code?  Back when I wrote a compiler for school, to which a formatter is similar, we had a few phases to convert it from Tiger C to ASM because of the optimisation step(s).  Last I looked, everything was run alphabetically, but I only spent an hour or so before being overwhelmed and going back to feature work.  So not sure if something similar is already done or could be.

**Comment by nicklockwood** [comment]
No, it's not that. SwiftFormat actually runs the rules repeatedly until there are no further changes detected.

It's more just that options like `--allman` are not symmetrical. It's always safe for me to make a line shorter, but it's not always safe for me to make it longer, so moving a brace onto a new line is applied in more cases than moving it back.

This is generally not a problem because if someone using `--allman false` wants to move the brace back to the previous line they can do so and SwiftFormat won't override their choice.

But you are using SwiftFormat in quite an unusual way: I don't know of anybody else who formats their code one way for themselves and then applies different formatting before submitting it to their team repo. I don't think it's wrong to do that, but it wasn't something I anticipated in the design of the tool.

Another problem is that you are using SwiftFormat to try to make your code comply with SwiftLint's formatting rules. This is something a lot of people do, and I try to support it, but in general if you are using both tools together it makes more sense to use SwiftFormat in --lint mode for validating the formatting, rather than hoping SwiftFormat and SwiftLint always have matching behavior (you can still use SwiftLint, but just disable any rules that relate to formatting).

**Comment by PompeiaPaetenari** [comment]
> Another problem is that you are using SwiftFormat to try to make your code comply with SwiftLint's formatting rules. This is something a lot of people do, and I try to support it, but in general if you are using both tools together it makes more sense to use SwiftFormat in --lint mode for validating the formatting, rather than hoping SwiftFormat and SwiftLint always have matching behaviour (you can still use SwiftLint, but just disable any rules that relate to formatting).

Oh, yes, perhaps I should bring that up then.  The team has very strict guidelines around keeping a balanced amount of dis/enabled SwiftLint rules.  However, for the most part, they want to have formatting done in a "I do not need to think about it" way and have it happen.  As far as I have seen, other than the error in the OP, SwiftLint only has the other check for line length.  I tried to add the SwiftFormat rule for that once, but they did not like where it was breaking things up at some point.  Now we have a local SwiftLint warning and a CI failure for certain things like `TODO` and line-length.

> But you are using SwiftFormat in quite an unusual way: I don't know of anybody else who formats their code one way for themselves and then applies different formatting before submitting it to their team repo. I don't think it's wrong to do that, but it wasn't something I anticipated in the design of the tool.

A lot of this comes from my background of VB, C, C++, and Python where examples in classes and books, and how I used them for assignments, were all with allman style.  I find it exceedingly hard to visualise a code block unless there are clear indications of indentation, and the braces are on their own line to show the start and end of it, lined up in a column.  However, it seems the workplace is averse to this style, and prefers what I feel is nigh unreadable at times with braces on same line, so I need to rearrange the code to read more complex files.  I never had issues with this for C/C++ because I had formatters that easily swapped between the two, and in fact was very glad to find SwiftFormat did the same for me (unlike gofmt and its horrible compiler friend), and I could make the jump from backend to Mobile without going insane trying to read code.
For now, I can selectively discard changes in Fork around these kind of format changes, but I figured it would be something obtainable to freely swap back and forth (symmetric, as you said).

I guess I do not quite understand the line-lingth concern when you do have that handy rule to break things up, unless there are still lines that do not break well, and perhaps that ties back into why the team removed the rule after I added it a while back.

**Comment by nicklockwood** [comment]
I've fixed this for now by setting a default max line width. It will now unwrap closure braces when `--allman false` if the line won't exceed 100 characters. If that's not good enough, you can set the limit with `--maxwidth 120` (or whatever).

**Comment by nicklockwood** [comment]
(Setting --maxwidth 120 should actually work with the currently-released version of SwiftFormat as well)

**Comment by nicklockwood** [comment]
@PompeiaPaetenari fixed in 0.47.3
