### ISSUE TITLE
Handling unusedArguments in delegate methods

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#83]
I don't know if this is a bug or not, but this [kind of] replacement feels strange.

From:
```
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath)
```

To:
```
func tableView(_: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath)
```

While I understand why it's happening, I'm wondering if there's a way to leave it in for delegate methods. 

In practice this seems like an especially common scenario (in delegate methods), for example if your spec changes and you have to add `tableView.deselectRow(at: indexPath)` into the function body, and have to add the variable back to the function declaration.

For now I've added `--disable unusedArguments` to avoid this, but just a suggestion, because I like the other times unusedArguments are stripped out.

**Comment by nicklockwood** [comment]
@mergesort when you say "other times", do you mean just in closures, or are there scenarios where you like them to be removed from functions too?

**Comment by mergesort** [comment]
I took a few minutes to reflect on how I feel SwiftFormat should approach the problem, and why, I would love to know if what I'm thinking makes sense.

• Removing unused closure parameters: A+ as it is, keep that.

• Removing unused arguments from functions: If it's intention is to provide a semantic representation of what should be expected at the call-site would not just `_` the unused parameter, but actually remove the parameter from the function. In practice this flag did help me catch a bug where I was unwittingly not using an argument in a function, so I can already see how it's helpful, but do not think that adding `_` is the best way to approach the task.

• Removing unused arguments from delegate methods: Delegate methods should keep their body as is, because they have to conform to the protocol, and the assumption is that all the parameters in the function declaration are there for the function body to use, if necessary.

I don't know if it's possible to break down functions to such granularity in SwiftFormat, but if not I would err on the side of caution, and offer 2 flags, `--disable unusedClosureArguments` and `--disable unusedFunctionArguments` if possible.

**Comment by nicklockwood** [comment]
@mergesort thanks for the detailed feedback, I'll address it below in detail, but tl;dr in SwiftFormat 0.24 (just released) you can now use `--stripunusedargs closure-only` to get the effect you were asking for.

**Comment by nicklockwood** [comment]
>Removing unused arguments from functions: If it's intention is to provide a semantic representation of what should be expected at the call-site would not just _ the unused parameter, but actually remove the parameter from the function.

This isn't a viable option for SwiftFormat currently, because it operates purely at a token level. It can scan the body of a function to see if an argument is used, but it can't know if the function itself is used elsewhere, and update all the call sites.

In any case, there are various hard-to-detect situations (besides delegates/protocols) where you would not want it to modify the function signature - for example if the function is called dynamically at runtime.

Finally, that simply isn't the purpose of the feature. The idea is to help you catch bugs by alerting you to the fact that an argument is unused, not to streamline your API. Not using an argument is not necessarily a bug, but it might be, so inserting a visual indication that the argument is unused draws your attention to that fact. Actually removing the argument from the signature would be overreaching, as you may have a good reason for keeping it there (e.g. retaining backwards compatibility with an earlier API, or preparing for a future requirement).

> In practice this flag did help me catch a bug where I was unwittingly not using an argument in a function, so I can already see how it's helpful, but do not think that adding _ is the best way to approach the task.

It's the way only way I know of in Swift to indicate that an argument is unused without changing the public signature of the method. A possible alternative would be to insert a comment, but then that wouldn't be enforced by the compiler, so if you later did start using the argument, the comment would remain, unlike `_`, which would have to be removed in order for the argument to be used.

> Removing unused arguments from delegate methods: Delegate methods should keep their body as is, because they have to conform to the protocol, and the assumption is that all the parameters in the function declaration are there for the function body to use, if necessary.

This only applies to the public/external argument names, which SwiftFormat doesn't modify. You are free to set the internal names to whatever you want, including `_` to indicate that you aren't using them, and it doesn't affect conformance to the protocol at all.

Here are the arguments for and against this feature, as I see them:

For:

* Inserting `_` documents visibly that the argument is unused. If you meant to use the argument, it alerts you that you didn't.

* It also enforces that the argument is unused it at the compiler level, so if you didn't mean to use it, it prevents you from accidentally using it until you remove the `_`.

Against:

* It looks a bit weird

* If you later decide to use the argument, you may have to retype its internal name, which has been deleted. Usually this name fairly obvious from the context, and it doesn't actually matter what you call it anyway as far as the compiler is concerned, but I recognise that it might be a PiTA if SwiftFormat keeps removing arguments you were planning to use later.

I think the second argument against is the most compelling, which is why I've added an option to selectively disable the feature. If you're more concerned about the weird-lookingness, there's also an intermediate option `--stripunusedargs unnamed-only` that only removes the internal name for unnamed arguments, which doesn't look quite so strange.

Anyway, thanks for taking the time to think about it, your feedback is always appreciated!
