### ISSUE TITLE
Feature Request: Xcode 12 indentation

### ISSUE THREAD

**Issue by Parabak** [nicklockwood/SwiftFormat#855]
Hi,

I failed to achieve  Xcode 12 indentation for lines longer then `maxWidth` as shown in [examle](https://twitter.com/olebegemann/status/1275335567497199616?lang=en), is it possible already? 

Best regards, Alex.

**Comment by nicklockwood** [comment]
guard statement indenting in SwiftFormat matches Xcode's behavior, but it won't wrap each case automatically.

**Comment by Parabak** [comment]
Thanks for quick reply!

Please have a look into following example, maybe I'm missing smth 🤔
```
guard let foo = foo, let bar = bar, let longConditiion = longCondition else { break }
```
`maxWidth` e.g. 40
desired output is:
```
guard let foo = foo,
      let bar = bar,
      let longConditiion = longCondition
else { 
   break 
}
```
is it possible with the current Rules set?

**Comment by nicklockwood** [comment]
No, this will currently be formatted as:

```swift
guard let foo = foo, let bar = bar,
      let longCondition =
      longCondition else { break }
```

**Comment by nicklockwood** [comment]
There is currently no rule to auto-wrap at commas in `guard`, or to wrap `{ break }` onto multiple lines.

**Comment by Parabak** [comment]
I would like to try to prepare a MR for that, what would you say? `wrapArguments` already has an option `--wrapcoonditions`, 
so maybe some `wrapConditionalStatements` rules? I believe it should be a rule rather then an option 🤔

**Comment by nicklockwood** [comment]
I think the logic to do this is mostly already implemented in `wrapArguments`, so there's probably no point having a separate rule. It's just a matter of adding to a configuration option to make it always wrap instead of only when the line is already broken.

I'd also prefer it to be an option because there are a few possibilities for how it might work - either it should always wrap at every comma, or only when the line length exceeds --maxwidth, so user should probably be able to choose between "always", "never", "auto" or something.

I've struggled with how to name this option, because people have asked for the same thing for arguments, so it's not specific to conditionals. If `--wrapconditions` and `--wrapparameters` etc. weren't already taken they'd be perfect.

If you're keen to implement the feature, mayeb you can do it with placehold argument names for now, and we can figure out good names once the feature is working?

**Comment by nicklockwood** [comment]
It's not very memorable, but `--conditionwrap always/never/auto` would probably work, then we could have `--parameterwrap`, `--collectionwrap`, etc as well with same semantics.

**Comment by Parabak** [comment]
agreed, let's start with `--conditionwrap always/never/auto`. Closing the ticket and let u know how it goes later on.
